"""Reproduce tab:signbit_methods from results/signbit_original_gt.csv.

This script runs NO FAISS. It reads the single sign-bit method-comparison
artifact and reproduces the 16-cell table that backs the paper's claim that
PMC helps every sign-based quantizer (BinaryFlat, BinaryIVF, RotatedBinary,
RaBitQ) across all four cross-modal directions.

Each cell is reported as vanilla/pmc R@100 at 2 decimals (leading-zero stripped),
exactly matching the manuscript's reporting convention.

Outputs:
  - stdout: human-readable table + LaTeX rows
  - results/tab1_signbit_methods_reproduced.csv
"""

from __future__ import annotations

import argparse
import csv
from decimal import Decimal, ROUND_HALF_UP
from pathlib import Path

# --- Configuration ----------------------------------------------------------

# Row order (methods) and column order (directions) as in tab:signbit_methods.
METHODS = ["BinaryFlat", "BinaryIVF", "RotatedBinary", "RaBitQ"]
DIRECTIONS = ["text2image", "image2text", "text2audio", "audio2text"]
VARIANTS = ["vanilla", "pmc_a1"]

DIRECTION_LABELS = {
    "text2image": "t->i",
    "image2text": "i->t",
    "text2audio": "t->a",
    "audio2text": "a->t",
}

FIELDNAMES = ["method", "direction", "r100_vanilla", "r100_pmc"]


# --- IO helpers --------------------------------------------------------------

def find_project_root() -> Path:
    for parent in Path(__file__).resolve().parents:
        if (parent / "results").is_dir():
            return parent
    raise RuntimeError("Could not find project root containing results/")


PROJECT_ROOT = find_project_root()
RESULTS_DIR = PROJECT_ROOT / "results"
SOURCE_CSV = RESULTS_DIR / "signbit_original_gt.csv"
OUTPUT_CSV = RESULTS_DIR / "tab1_signbit_methods_reproduced.csv"


def read_csv_rows(path: Path) -> list[dict[str, str]]:
    with path.open(newline="", encoding="utf-8") as handle:
        return list(csv.DictReader(handle))


# --- Formatting --------------------------------------------------------------

def round_half_up(value: float, digits: int) -> float:
    quant = Decimal("1") if digits == 0 else Decimal("1").scaleb(-digits)
    return float(Decimal(str(value)).quantize(quant, rounding=ROUND_HALF_UP))


def fmt_recall(value: float, digits: int = 2) -> str:
    out = f"{round_half_up(value, digits):.{digits}f}"
    return out[1:] if out.startswith("0") else out


# --- Lookups -----------------------------------------------------------------

def pick(rows: list[dict[str, str]], method: str, direction: str,
         variant: str) -> dict[str, str]:
    hits = [
        r for r in rows
        if r["method"] == method and r["direction"] == direction
        and r["variant"] == variant
    ]
    if len(hits) != 1:
        raise ValueError(
            f"Expected one row for method={method} dir={direction} "
            f"variant={variant}, got {len(hits)}"
        )
    return hits[0]


def r100_at(rows: list[dict[str, str]], method: str, direction: str,
            variant: str) -> float:
    return float(pick(rows, method, direction, variant)["r100"])


# --- Build -------------------------------------------------------------------

def build_records(rows: list[dict[str, str]]) -> list[dict[str, str]]:
    records: list[dict[str, str]] = []
    for method in METHODS:
        for direction in DIRECTIONS:
            van = r100_at(rows, method, direction, "vanilla")
            pmc = r100_at(rows, method, direction, "pmc_a1")
            records.append({
                "method": method,
                "direction": direction,
                "r100_vanilla": fmt_recall(van),
                "r100_pmc": fmt_recall(pmc),
            })
    return records


def write_output_csv(records: list[dict[str, str]]) -> None:
    RESULTS_DIR.mkdir(parents=True, exist_ok=True)
    with OUTPUT_CSV.open("w", newline="", encoding="utf-8") as handle:
        writer = csv.DictWriter(handle, fieldnames=FIELDNAMES)
        writer.writeheader()
        writer.writerows(records)


# --- Reporting ---------------------------------------------------------------

def print_console_table(records: list[dict[str, str]]) -> None:
    by_method: dict[str, dict[str, dict[str, str]]] = {}
    for r in records:
        by_method.setdefault(r["method"], {})[r["direction"]] = r

    header = f"{'Method':<14}" + "".join(
        f"{DIRECTION_LABELS[d] + ' (v/p)':>14}" for d in DIRECTIONS
    )
    print(header)
    print("-" * len(header))
    for method in METHODS:
        cells = by_method[method]
        line = f"{method:<14}"
        for d in DIRECTIONS:
            c = cells[d]
            line += f"{c['r100_vanilla'] + '/' + c['r100_pmc']:>14}"
        print(line)


def print_latex_rows(records: list[dict[str, str]]) -> None:
    print("% --- auto-generated by reproduce_tab1_signbit_methods.py ---")
    print("% columns: Method & t->i (v/p) & i->t (v/p) & t->a (v/p) & a->t (v/p)")
    by_method: dict[str, dict[str, dict[str, str]]] = {}
    for r in records:
        by_method.setdefault(r["method"], {})[r["direction"]] = r
    for method in METHODS:
        cells = by_method[method]
        parts = []
        for d in DIRECTIONS:
            c = cells[d]
            parts.append(f"{c['r100_vanilla']}\\,/\\,\\textbf{{{c['r100_pmc']}}}")
        print(f"{method:<14} & " + " & ".join(parts) + " \\\\")


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Reproduce tab:signbit_methods from signbit_original_gt.csv"
    )
    parser.parse_args()

    if not SOURCE_CSV.exists():
        raise FileNotFoundError(f"Missing source CSV: {SOURCE_CSV}")
    rows = read_csv_rows(SOURCE_CSV)
    records = build_records(rows)
    write_output_csv(records)
    print_console_table(records)
    print()
    print_latex_rows(records)
    print(f"\nWrote: {OUTPUT_CSV}")


if __name__ == "__main__":
    main()
